# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95c872ee81f6381a96bce2cb38f75535fa1e774bbefff40c8b52c636e7269c3fd8a0914193ef6c92d589f91c4cb19709e87b2f304a72464b3fe52dc317333ebe

test:
  secret_key_base: 1f40993d5951ae3c6b3e4aadf0263b4d055048195c7ebcd7227e55f28139b412be3229df109bb027a3d9d70c366e8e861c8ca2f527f78d4a61a77c748eb591b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
